_dt_system:
    resource: "@CoreBundle/Resources/config/routing.xml"



#_dt_user_profile:
#    resource: "@UserBundle/Resources/config/routing/profile.xml"

#_dt_user_register:
#    resource: "@UserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#_dt_user_resetting:
#    resource: "@UserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#_dt_user_change_password:
#    resource: "@UserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

#_dt_user_group:
#    resource: "@UserBundle/Resources/config/routing/group.xml"
#    prefix: /group
